# Generated by Django 5.1 on 2026-05-01 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('daily_calorie_target', models.IntegerField()),
                ('daily_protein_g', models.IntegerField()),
                ('daily_carbs_g', models.IntegerField()),
                ('daily_fat_g', models.IntegerField()),
                ('daily_fiber_g', models.IntegerField()),
                ('daily_water_ml', models.IntegerField()),
                ('claude_reasoning', models.TextField()),
                ('additional_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_number'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack_am', 'AM Snack'), ('snack_pm', 'PM Snack')], max_length=20)),
                ('meal_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('calories', models.IntegerField()),
                ('protein_g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('fiber_g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('ingredients', models.JSONField(default=list)),
                ('preparation_notes', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('additional_comments', models.TextField(blank=True)),
                ('health_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='health.healthplan')),
            ],
            options={
                'ordering': ['day_of_week', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack_am', 'AM Snack'), ('snack_pm', 'PM Snack')], max_length=20)),
                ('description', models.TextField()),
                ('estimated_calories', models.IntegerField(blank=True, null=True)),
                ('estimated_protein_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('estimated_carbs_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('estimated_fat_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('water_ml', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WellnessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('sleep_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sleep_quality', models.IntegerField()),
                ('bedtime', models.TimeField(blank=True, null=True)),
                ('wake_time', models.TimeField(blank=True, null=True)),
                ('mood_score', models.IntegerField()),
                ('stress_level', models.IntegerField()),
                ('energy_level', models.IntegerField()),
                ('mindfulness_done', models.BooleanField(default=False)),
                ('mindfulness_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('mindfulness_type', models.CharField(blank=True, choices=[('meditation', 'Meditation'), ('breathing', 'Breathing'), ('journaling', 'Journaling'), ('yoga', 'Yoga')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
