# Generated by Django 5.1 on 2026-05-01 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnesslog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='wellnesslog',
            unique_together={('user', 'date')},
        ),
    ]
