# Generated by Django 5.1 on 2026-05-01 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('total_workout_days', models.IntegerField()),
                ('total_running_days', models.IntegerField(default=0)),
                ('weekly_goal_summary', models.TextField()),
                ('claude_reasoning', models.TextField()),
                ('additional_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_of_week', models.CharField(max_length=10)),
                ('day_type', models.CharField(choices=[('strength', 'Strength'), ('running', 'Running'), ('yoga', 'Yoga'), ('active_recovery', 'Active Recovery'), ('rest', 'Rest')], max_length=20)),
                ('focus_area', models.CharField(choices=[('upper_body', 'Upper Body'), ('lower_body', 'Lower Body'), ('full_body', 'Full Body'), ('core', 'Core'), ('cardio', 'Cardio')], max_length=20)),
                ('estimated_duration_minutes', models.IntegerField()),
                ('warmup_description', models.TextField(blank=True)),
                ('cooldown_description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('fitness_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to='fitness.fitnessplan')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RunningStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('easy', 'Easy'), ('interval', 'Interval'), ('tempo', 'Tempo'), ('long_run', 'Long Run'), ('fartlek', 'Fartlek')], max_length=20)),
                ('total_distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_duration_minutes', models.IntegerField()),
                ('pace_target', models.CharField(max_length=50)),
                ('structure', models.JSONField(default=list)),
                ('heart_rate_zone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('workout_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='running_strategy', to='fitness.workoutday')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=200)),
                ('section', models.CharField(choices=[('warmup', 'Warmup'), ('main', 'Main'), ('cooldown', 'Cooldown'), ('pre_run', 'Pre-Run'), ('post_run', 'Post-Run')], max_length=20)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rest_seconds', models.IntegerField(default=60)),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('additional_comments', models.TextField(blank=True)),
                ('exercise_cache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.exercisecache')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='fitness.workoutday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('perceived_exertion', models.IntegerField(blank=True, null=True)),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fitness.workoutday')),
            ],
            options={
                'unique_together': {('user', 'workout_day')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_completed', models.IntegerField(default=0)),
                ('reps_completed', models.JSONField(default=list)),
                ('weight_kg', models.JSONField(default=list)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('skip_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.workoutexercise')),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='fitness.workoutlog')),
            ],
        ),
    ]
