# Generated by Django 5.1 on 2026-05-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exerciselog',
            unique_together={('workout_log', 'workout_exercise')},
        ),
    ]
