# Generated by Django 5.1 on 2026-06-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_exerciselog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningstrategy',
            name='heart_rate_zone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
