# Generated by Django 5.1 on 2026-06-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_increase_heart_rate_zone_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningstrategy',
            name='pace_target',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='intensity',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20),
        ),
    ]
