# Generated by Django 5.1 on 2026-06-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_increase_intensity_and_pace_target_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningstrategy',
            name='heart_rate_zone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
