# Generated by Django 5.1 on 2026-05-01 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('fitness_experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('primary_goal', models.TextField()),
                ('diet_type', models.CharField(choices=[('omnivore', 'Omnivore'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('other', 'Other')], max_length=20)),
                ('food_allergies', models.JSONField(default=list)),
                ('food_preferences', models.TextField(blank=True)),
                ('daily_routine', models.TextField(blank=True)),
                ('wake_time', models.TimeField()),
                ('sleep_time', models.TimeField()),
                ('work_schedule', models.CharField(choices=[('9-5', '9–5'), ('shift', 'Shift work'), ('flexible', 'Flexible')], max_length=20)),
                ('workout_days_per_week', models.IntegerField()),
                ('preferred_workout_days', models.JSONField(default=list)),
                ('running_days_per_week', models.IntegerField(default=0)),
                ('workout_location', models.CharField(choices=[('gym', 'Gym'), ('home', 'Home'), ('outdoor', 'Outdoor')], max_length=20)),
                ('available_equipment', models.JSONField(default=list)),
                ('injury_history', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('notification_email', models.EmailField(max_length=254)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('additional_comments', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
