# Generated by Django 5.1 on 2026-06-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='average_cycle_length',
            field=models.IntegerField(default=28),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tracks_cycle',
            field=models.BooleanField(default=False),
        ),
    ]
