# Generated by Django 5.1 on 2026-05-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wger_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('primary_muscles', models.JSONField(default=list)),
                ('secondary_muscles', models.JSONField(default=list)),
                ('equipment', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('gif_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
