# Generated by Django 5.1 on 2026-05-01 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('fitness_status', models.CharField(choices=[('on_track', 'On Track'), ('overshooting', 'Overshooting'), ('underachieving', 'Underachieving'), ('no_data', 'No Data')], default='no_data', max_length=20)),
                ('health_status', models.CharField(choices=[('on_track', 'On Track'), ('overshooting', 'Overshooting'), ('underachieving', 'Underachieving'), ('no_data', 'No Data')], default='no_data', max_length=20)),
                ('body_preview', models.TextField()),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
